// SPDX-License-Identifier: GPL-2.0-only
//! At-rest envelope encryption (AES-256-GCM).
//!
//! Applied to object-store payloads so screenshots on disk are ciphertext —
//! the analogue of Recall's enclave-sealed storage. The key is a per-client
//! 256-bit secret generated by the server at provisioning time; on the client
//! side the same role is played by DPAPI-NG, so ciphertext never crosses the
//! wire unprotected.

use aes_gcm::{
    aead::{rand_core::RngCore, Aead, KeyInit, OsRng, Payload},
    Aes256Gcm, Key, Nonce,
};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum CryptoError {
    #[error("ciphertext too short")]
    Truncated,
    #[error("decryption failed")]
    Decrypt,
}

/// AES-256-GCM envelope sealer. Wire/storage format: `nonce(12) || ciphertext`.
pub struct EnvelopeCipher {
    inner: Aes256Gcm,
}

impl EnvelopeCipher {
    pub fn new(key: &[u8; 32]) -> Self {
        Self { inner: Aes256Gcm::new(Key::<Aes256Gcm>::from_slice(key)) }
    }

    pub fn generate_key() -> [u8; 32] {
        let mut k = [0u8; 32];
        OsRng.fill_bytes(&mut k);
        k
    }

    /// Seal with optional associated data (e.g. the image token binds the
    /// ciphertext to its object key, preventing blob swapping).
    pub fn seal(&self, aad: &[u8], plaintext: &[u8]) -> Vec<u8> {
        let mut nonce = [0u8; 12];
        OsRng.fill_bytes(&mut nonce);
        let ct = self
            .inner
            .encrypt(Nonce::from_slice(&nonce), Payload { msg: plaintext, aad })
            .expect("aes-gcm encrypt cannot fail for valid key");
        let mut out = Vec::with_capacity(12 + ct.len());
        out.extend_from_slice(&nonce);
        out.extend_from_slice(&ct);
        out
    }

    pub fn open(&self, aad: &[u8], sealed: &[u8]) -> Result<Vec<u8>, CryptoError> {
        if sealed.len() < 12 + 16 {
            return Err(CryptoError::Truncated);
        }
        let (nonce, ct) = sealed.split_at(12);
        self.inner
            .decrypt(Nonce::from_slice(nonce), Payload { msg: ct, aad })
            .map_err(|_| CryptoError::Decrypt)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_and_aad_binding() {
        let c = EnvelopeCipher::new(&EnvelopeCipher::generate_key());
        let sealed = c.seal(b"tok-1", b"hello jpeg bytes");
        assert_eq!(c.open(b"tok-1", &sealed).unwrap(), b"hello jpeg bytes");
        // Wrong AAD must fail.
        assert!(c.open(b"tok-2", &sealed).is_err());
    }
}
